version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Ifex370/juice-shop"

[[analyzers]]
name = "php"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "angularjs",
    "angular",
    "react",
    "vue"
  ]
  environment = [
    "nodejs",
    "jquery",
    "mongo"
  ]

[[analyzers]]
name = "docker"

[[analyzers]]
name = "ansible"